#user  nobody;
worker_processes  1;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

http {
    server {
        listen       80;
        server_name  localhost;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }


    server {
        listen 8000 ssl;
        # server_name 127.0.0.1;

        ssl_certificate C:/Git-Hub/KIBrown031.github.io/nginx/ssl/server.crt;
        ssl_certificate_key C:/Git-Hub/KIBrown031.github.io/nginx/ssl/server.key;

        # Increase maximum allowed file upload size (default is only 1MB)
        client_max_body_size 500M;  # set to 0 to ignore file size

        location / {
            # root /share/node;

            # 1. Handle the browser Preflight OPTIONS check right here in Nginx
            if ($request_method = 'OPTIONS') {
                # add_header 'Access-Control-Allow-Origin' 'http://127.0.0.1:8080' always;
                add_header 'Access-Control-Allow-Origin' 'https://kibrown031.github.io' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204; # Instantly reply with successful empty body to the browser
            }

            # 2. Inject headers for the actual PUT file upload request
            # add_header 'Access-Control-Allow-Origin' 'http://127.0.0.1:8080' always;
            add_header 'Access-Control-Allow-Origin' 'https://kibrown031.github.io' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;

            # 3. Forward the traffic safely down to your internal Node app (running on port 3000)
            proxy_pass http://10.10.1.222:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
